### ISSUE TITLE
Ok, it only works if you don't have or create any new save files before a "steal".

### ISSUE THREAD

**Issue by AJAL8000** [MasterAli2/SaveStealer#2]
![image](https://github.com/MasterAli2/SaveStealer/assets/55171241/30378cc2-1177-4a80-af79-250419727752)
When you enter the command, nothing happens.
It only passes the next line, it does not generate any copy.

**Comment by MasterAli2** [comment]
I gave a potential fix in the discord forum
https://discord.com/channels/1168655651455639582/1205484259914027008

This issue is probably with better saves.

**Comment by AJAL8000** [comment]
First: I can't access the link.
Second: Why don't you update the mod then?
Third: Which Discord?

> I gave a potential fix in the discord forum https://discord.com/channels/1168655651455639582/1205484259914027008
> 
> This issue is probably with better saves.

**Comment by MasterAli2** [comment]
When updating the mod or its dependencies the mod breaks, a fix would to delete the save files in the app data (make sure to have a backup), or not updating the mod or its dependency unless necessary.

Also here is the discord: if you need help finding the app data ask for help here (deleting the app data will delete all of your saved games)

https://discord.com/invite/lcmod

**Comment by AJAL8000** [comment]
Okay, I've already used it on several occasions and yes, theoretically it does work but only if you don't have any savefiles or you have stolen a previous savefile. Which means you have to save your savefiles separately in another folder if you want to have more than one.
I'm sorry I just confirmed that it works for me, I should have done it a long time ago but I forgot that I had made this Issue which will remain as an Issue since it is a little annoying to do, but manageable.

**Comment by MasterAli2** [comment]
I decided to update the mod, to use a better API for the terminal command and until a new alternative appears im gonan give the option to either use or not use lc better saves. it would take 1 or 2 months cuz of school and im working on other things
